@startuml Purchase
skinparam Monochrome true
skinparam Shadowing false
hide empty description

[*] -> Created
Created: entry/ seller = payable(msg.sender)
Created: entry/ value = msg.value / 2
Created ---> Aborting: abort() \n[sent from seller]

Aborting: entry/ emit Aborted()
Aborting: entry/ transfer balance to seller
Aborting --> Inactive

Created --> Locked: confirmPurchase() \n[msg.value == 2 * value]

Locked: entry/ emit PurchaseConfirmed()
Locked: entry/ buyer = payable(msg.sender)
Locked --> Release: confirmReceived() [sent from buyer]

Release: entry/ emit ItemReceived()
Release: entry/ transfer value to buyer
Release --> Refunding: refundSeller() [sent from seller]

Refunding: entry/ emit SellerRefunded()
Refunding: entry/ transfer 3 * value to seller
Refunding --> Inactive
Inactive --> [*]


@enduml
